name: Enviar Mensagem Telegram
on:
  schedule:
    - cron: '35 0 * * *'  # Executa todos os dias às 06:00 UTC (ajuste conforme necessário)
jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalar Dependências
        run: npm install

      - name: Enviar Mensagem Telegram
        run: node sendTelegramMessage.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}